language: python
python:
  - "2.7"
install:
  # Install in virtual env.
  - pip install python-daemon
  - pip install parsedatetime
  - python setup.py install
  # Also install for use with sudo.
  - sudo pip install python-daemon
  - sudo pip install parsedatetime
  - sudo python setup.py install
script:
  - . tests/run-atd.sh
sudo: required
